services:
  mysql_test:
    image: mysql:8.0
    container_name: nest_mysql_test
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    tmpfs:
      - /var/lib/mysql # Use RAM for faster IO and auto-cleanup on stop
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5

  nats_test:
    image: nats:2.10-alpine
    container_name: nest_nats_test
    ports:
      - '4222:4222'
      - '8222:8222' # HTTP monitoring port
    command: ['-js', '-m', '8222'] # Enable JetStream and monitoring
