services:
  mysql_auth_test:
    image: mysql:8.0
    container_name: nest_mysql_auth_test
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./docker/mysql-init/auth:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5

  mysql_messenger_test:
    image: mysql:8.0
    container_name: nest_mysql_messenger_test
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger_db_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./docker/mysql-init/messenger:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5

  nats_test:
    image: nats:2.10-alpine
    container_name: nest_nats_test
    ports:
      - '4222:4222'
      - '8222:8222'
    command: ['-js', '-m', '8222']
