apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: meeting-api-gateway-secrets
  namespace: $NAMESPACE
  labels:
    app: meeting-api-gateway
    env: $NAMESPACE
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/$PROJECT_ID/secrets/$GCP_SECRET_NAME/versions/$SECRET_VERSION"
        path: ".env.meeting-api-gateway"
