apiVersion: v1
kind: ConfigMap
metadata:
  name: meeting-api-gateway-config
  labels:
    app: meeting-api-gateway
    env: $NAMESPACE
data:
  PORT: '3000'
  BASE_URL: 'http://meeting-api-gateway.$NAMESPACE.svc.cluster.local'
  # Add other non-sensitive environment variables here
