kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: meeting-gateway
  annotations:
    networking.gke.io/certmap: garbadge-shop-map
spec:
  # This GatewayClass uses a global external Application Load Balancer.
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
