kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: meeting-gateway
  namespace: $NAMESPACE
  annotations:
    networking.gke.io/certmap: meeting-gateway-certmap
    networking.gke.io/static-ip: meeting-gateway-ip
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        options: {}
    - name: http
      protocol: HTTP
      port: 80
