apiVersion: v1
kind: Service
metadata:
  name: meeting-api-gateway
  labels:
    app: meeting-api-gateway
    env: $NAMESPACE
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"3000":{}}}'
spec:
  selector:
    app: meeting-api-gateway
    env: $NAMESPACE
  ports:
    - name: http
      protocol: TCP
      port: 3000 # <--- Change this from 80 to 3000
      targetPort: 3000
  type: ClusterIP
