apiVersion: v1
kind: ServiceAccount
metadata:
  name: meeting-api-gateway-sa
  namespace: $NAMESPACE
  labels:
    app: meeting-api-gateway
    env: $NAMESPACE
  annotations:
    iam.gke.io/gcp-service-account: $GSA_NAME@$PROJECT_ID.iam.gserviceaccount.com
